basePath: /
definitions:
  model.AliyunOssStsRes:
    properties:
      accessKeyId:
        type: string
      accessKeySecret:
        type: string
      bucket:
        type: string
      expiration:
        type: string
      region:
        type: string
      stsToken:
        type: string
    type: object
  model.SmsReq:
    properties:
      captchaCode:
        description: captcha 验证码
        type: string
      phone:
        description: 手机号
        type: string
    required:
    - captchaCode
    - phone
    type: object
  model.SmsRes:
    properties:
      id:
        description: 任务ID
        type: string
    type: object
info:
  contact: {}
  title: 极光出行API - 公共api
  version: "1.0"
paths:
  /common/captcha:
    get:
      consumes:
      - image/png
      description: 生成的图片验证码有效时间为10分钟
      operationId: CaptchaGenerate
      produces:
      - image/png
      responses:
        "200":
          description: ok
          headers:
            "X-Captcha-Id\ttrue":
              description: Captcha验证码ID
              type: string
          schema:
            type: string
      summary: C1 生成图片验证码
      tags:
      - Communal - 公共接口
  /common/oss/token:
    get:
      consumes:
      - application/json
      description: 上传文件必须，单次获取有效时间为1个小时
      operationId: AliyunOssToken
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.AliyunOssStsRes'
      summary: C3 获取阿里云oss临时凭证
      tags:
      - Communal - 公共接口
  /common/sms:
    post:
      consumes:
      - application/json
      description: 上传文件必须，单次获取有效时间为1个小时
      operationId: SendSmsCode
      parameters:
      - description: 请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SmsReq'
      - description: Captcha验证码ID
        in: header
        name: X-Captcha-Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.SmsRes'
      summary: C2 发送短信验证码
      tags:
      - Communal - 公共接口
swagger: "2.0"
