# 安装 pre-commit: pip install pre-commit 或 brew install pre-commit (参见 https://pre-commit.com/#install)
# 安装触发器: pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: golangci-lint
#      - id: no-go-testing
#      - id: go-unit-tests
