#!/usr/bin/env bash

PORT=26615

if [ "$1" == 'next' ]; then
    PORT=26611
fi

echo "同步数据库: $PORT"

ssh root@118.116.4.16 -p "$PORT" "sudo -u postgres pg_dump -U postgres -d auroraride --exclude-table exchange --exclude-table battery_flow -f /var/lib/postgresql/auroraride.sql; cd /var/lib/postgresql/; rm -rf auroraride.sql.zip; zip auroraride.sql.zip auroraride.sql"
scp -P "$PORT" root@118.116.4.16:/var/lib/postgresql/auroraride.sql.zip ~/Downloads/_sql/
cd ~/Downloads/_sql/ || return
rm -rf auroraride.sql
unzip auroraride.sql.zip
rm -rf auroraride.sql.zip
dropdb -U "$(whoami)" auroraride
createdb auroraride
psql -d auroraride -U "$(whoami)" -c "SET timezone = 'Asia/Shanghai'; CREATE EXTENSION postgis; CREATE EXTENSION pg_trgm; CREATE EXTENSION btree_gin;"
psql -d auroraride -U "$(whoami)" -f auroraride.sql
ssh root@118.116.4.16 -p "$PORT" "rm -rf /var/lib/postgresql/auroraride.sql.zip && rm -rf /var/lib/postgresql/auroraride.sql"
#rm -rf ~/Downloads/_sql/auroraride.sql
