// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/auroraride/aurservd/internal/ent/batterynew"
	"github.com/auroraride/aurservd/internal/ent/city"
	"github.com/auroraride/aurservd/internal/ent/predicate"
)

// BatteryNewQuery is the builder for querying BatteryNew entities.
type BatteryNewQuery struct {
	config
	ctx        *QueryContext
	order      []batterynew.OrderOption
	inters     []Interceptor
	predicates []predicate.BatteryNew
	withCity   *CityQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BatteryNewQuery builder.
func (bnq *BatteryNewQuery) Where(ps ...predicate.BatteryNew) *BatteryNewQuery {
	bnq.predicates = append(bnq.predicates, ps...)
	return bnq
}

// Limit the number of records to be returned by this query.
func (bnq *BatteryNewQuery) Limit(limit int) *BatteryNewQuery {
	bnq.ctx.Limit = &limit
	return bnq
}

// Offset to start from.
func (bnq *BatteryNewQuery) Offset(offset int) *BatteryNewQuery {
	bnq.ctx.Offset = &offset
	return bnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bnq *BatteryNewQuery) Unique(unique bool) *BatteryNewQuery {
	bnq.ctx.Unique = &unique
	return bnq
}

// Order specifies how the records should be ordered.
func (bnq *BatteryNewQuery) Order(o ...batterynew.OrderOption) *BatteryNewQuery {
	bnq.order = append(bnq.order, o...)
	return bnq
}

// QueryCity chains the current query on the "city" edge.
func (bnq *BatteryNewQuery) QueryCity() *CityQuery {
	query := (&CityClient{config: bnq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bnq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bnq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(batterynew.Table, batterynew.FieldID, selector),
			sqlgraph.To(city.Table, city.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, batterynew.CityTable, batterynew.CityColumn),
		)
		fromU = sqlgraph.SetNeighbors(bnq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BatteryNew entity from the query.
// Returns a *NotFoundError when no BatteryNew was found.
func (bnq *BatteryNewQuery) First(ctx context.Context) (*BatteryNew, error) {
	nodes, err := bnq.Limit(1).All(setContextOp(ctx, bnq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{batterynew.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bnq *BatteryNewQuery) FirstX(ctx context.Context) *BatteryNew {
	node, err := bnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BatteryNew ID from the query.
// Returns a *NotFoundError when no BatteryNew ID was found.
func (bnq *BatteryNewQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = bnq.Limit(1).IDs(setContextOp(ctx, bnq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{batterynew.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bnq *BatteryNewQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := bnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BatteryNew entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BatteryNew entity is found.
// Returns a *NotFoundError when no BatteryNew entities are found.
func (bnq *BatteryNewQuery) Only(ctx context.Context) (*BatteryNew, error) {
	nodes, err := bnq.Limit(2).All(setContextOp(ctx, bnq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{batterynew.Label}
	default:
		return nil, &NotSingularError{batterynew.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bnq *BatteryNewQuery) OnlyX(ctx context.Context) *BatteryNew {
	node, err := bnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BatteryNew ID in the query.
// Returns a *NotSingularError when more than one BatteryNew ID is found.
// Returns a *NotFoundError when no entities are found.
func (bnq *BatteryNewQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = bnq.Limit(2).IDs(setContextOp(ctx, bnq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{batterynew.Label}
	default:
		err = &NotSingularError{batterynew.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bnq *BatteryNewQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := bnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BatteryNews.
func (bnq *BatteryNewQuery) All(ctx context.Context) ([]*BatteryNew, error) {
	ctx = setContextOp(ctx, bnq.ctx, "All")
	if err := bnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BatteryNew, *BatteryNewQuery]()
	return withInterceptors[[]*BatteryNew](ctx, bnq, qr, bnq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bnq *BatteryNewQuery) AllX(ctx context.Context) []*BatteryNew {
	nodes, err := bnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BatteryNew IDs.
func (bnq *BatteryNewQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if bnq.ctx.Unique == nil && bnq.path != nil {
		bnq.Unique(true)
	}
	ctx = setContextOp(ctx, bnq.ctx, "IDs")
	if err = bnq.Select(batterynew.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bnq *BatteryNewQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := bnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bnq *BatteryNewQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bnq.ctx, "Count")
	if err := bnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bnq, querierCount[*BatteryNewQuery](), bnq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bnq *BatteryNewQuery) CountX(ctx context.Context) int {
	count, err := bnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bnq *BatteryNewQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bnq.ctx, "Exist")
	switch _, err := bnq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bnq *BatteryNewQuery) ExistX(ctx context.Context) bool {
	exist, err := bnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BatteryNewQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bnq *BatteryNewQuery) Clone() *BatteryNewQuery {
	if bnq == nil {
		return nil
	}
	return &BatteryNewQuery{
		config:     bnq.config,
		ctx:        bnq.ctx.Clone(),
		order:      append([]batterynew.OrderOption{}, bnq.order...),
		inters:     append([]Interceptor{}, bnq.inters...),
		predicates: append([]predicate.BatteryNew{}, bnq.predicates...),
		withCity:   bnq.withCity.Clone(),
		// clone intermediate query.
		sql:  bnq.sql.Clone(),
		path: bnq.path,
	}
}

// WithCity tells the query-builder to eager-load the nodes that are connected to
// the "city" edge. The optional arguments are used to configure the query builder of the edge.
func (bnq *BatteryNewQuery) WithCity(opts ...func(*CityQuery)) *BatteryNewQuery {
	query := (&CityClient{config: bnq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bnq.withCity = query
	return bnq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BatteryNew.Query().
//		GroupBy(batterynew.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bnq *BatteryNewQuery) GroupBy(field string, fields ...string) *BatteryNewGroupBy {
	bnq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BatteryNewGroupBy{build: bnq}
	grbuild.flds = &bnq.ctx.Fields
	grbuild.label = batterynew.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.BatteryNew.Query().
//		Select(batterynew.FieldCreatedAt).
//		Scan(ctx, &v)
func (bnq *BatteryNewQuery) Select(fields ...string) *BatteryNewSelect {
	bnq.ctx.Fields = append(bnq.ctx.Fields, fields...)
	sbuild := &BatteryNewSelect{BatteryNewQuery: bnq}
	sbuild.label = batterynew.Label
	sbuild.flds, sbuild.scan = &bnq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BatteryNewSelect configured with the given aggregations.
func (bnq *BatteryNewQuery) Aggregate(fns ...AggregateFunc) *BatteryNewSelect {
	return bnq.Select().Aggregate(fns...)
}

func (bnq *BatteryNewQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bnq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bnq); err != nil {
				return err
			}
		}
	}
	for _, f := range bnq.ctx.Fields {
		if !batterynew.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bnq.path != nil {
		prev, err := bnq.path(ctx)
		if err != nil {
			return err
		}
		bnq.sql = prev
	}
	return nil
}

func (bnq *BatteryNewQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BatteryNew, error) {
	var (
		nodes       = []*BatteryNew{}
		_spec       = bnq.querySpec()
		loadedTypes = [1]bool{
			bnq.withCity != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BatteryNew).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BatteryNew{config: bnq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(bnq.modifiers) > 0 {
		_spec.Modifiers = bnq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bnq.withCity; query != nil {
		if err := bnq.loadCity(ctx, query, nodes, nil,
			func(n *BatteryNew, e *City) { n.Edges.City = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bnq *BatteryNewQuery) loadCity(ctx context.Context, query *CityQuery, nodes []*BatteryNew, init func(*BatteryNew), assign func(*BatteryNew, *City)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*BatteryNew)
	for i := range nodes {
		if nodes[i].CityID == nil {
			continue
		}
		fk := *nodes[i].CityID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(city.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "city_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bnq *BatteryNewQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bnq.querySpec()
	if len(bnq.modifiers) > 0 {
		_spec.Modifiers = bnq.modifiers
	}
	_spec.Node.Columns = bnq.ctx.Fields
	if len(bnq.ctx.Fields) > 0 {
		_spec.Unique = bnq.ctx.Unique != nil && *bnq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bnq.driver, _spec)
}

func (bnq *BatteryNewQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(batterynew.Table, batterynew.Columns, sqlgraph.NewFieldSpec(batterynew.FieldID, field.TypeUint64))
	_spec.From = bnq.sql
	if unique := bnq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bnq.path != nil {
		_spec.Unique = true
	}
	if fields := bnq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, batterynew.FieldID)
		for i := range fields {
			if fields[i] != batterynew.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if bnq.withCity != nil {
			_spec.Node.AddColumnOnce(batterynew.FieldCityID)
		}
	}
	if ps := bnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bnq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bnq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bnq *BatteryNewQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bnq.driver.Dialect())
	t1 := builder.Table(batterynew.Table)
	columns := bnq.ctx.Fields
	if len(columns) == 0 {
		columns = batterynew.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bnq.sql != nil {
		selector = bnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bnq.ctx.Unique != nil && *bnq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range bnq.modifiers {
		m(selector)
	}
	for _, p := range bnq.predicates {
		p(selector)
	}
	for _, p := range bnq.order {
		p(selector)
	}
	if offset := bnq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bnq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bnq *BatteryNewQuery) Modify(modifiers ...func(s *sql.Selector)) *BatteryNewSelect {
	bnq.modifiers = append(bnq.modifiers, modifiers...)
	return bnq.Select()
}

type BatteryNewQueryWith string

var (
	BatteryNewQueryWithCity BatteryNewQueryWith = "City"
)

func (bnq *BatteryNewQuery) With(withEdges ...BatteryNewQueryWith) *BatteryNewQuery {
	for _, v := range withEdges {
		switch v {
		case BatteryNewQueryWithCity:
			bnq.WithCity()
		}
	}
	return bnq
}

// BatteryNewGroupBy is the group-by builder for BatteryNew entities.
type BatteryNewGroupBy struct {
	selector
	build *BatteryNewQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bngb *BatteryNewGroupBy) Aggregate(fns ...AggregateFunc) *BatteryNewGroupBy {
	bngb.fns = append(bngb.fns, fns...)
	return bngb
}

// Scan applies the selector query and scans the result into the given value.
func (bngb *BatteryNewGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bngb.build.ctx, "GroupBy")
	if err := bngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BatteryNewQuery, *BatteryNewGroupBy](ctx, bngb.build, bngb, bngb.build.inters, v)
}

func (bngb *BatteryNewGroupBy) sqlScan(ctx context.Context, root *BatteryNewQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bngb.fns))
	for _, fn := range bngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bngb.flds)+len(bngb.fns))
		for _, f := range *bngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BatteryNewSelect is the builder for selecting fields of BatteryNew entities.
type BatteryNewSelect struct {
	*BatteryNewQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bns *BatteryNewSelect) Aggregate(fns ...AggregateFunc) *BatteryNewSelect {
	bns.fns = append(bns.fns, fns...)
	return bns
}

// Scan applies the selector query and scans the result into the given value.
func (bns *BatteryNewSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bns.ctx, "Select")
	if err := bns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BatteryNewQuery, *BatteryNewSelect](ctx, bns.BatteryNewQuery, bns, bns.inters, v)
}

func (bns *BatteryNewSelect) sqlScan(ctx context.Context, root *BatteryNewQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bns.fns))
	for _, fn := range bns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bns *BatteryNewSelect) Modify(modifiers ...func(s *sql.Selector)) *BatteryNewSelect {
	bns.modifiers = append(bns.modifiers, modifiers...)
	return bns
}
