// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/auroraride/aurservd/internal/ent/predicate"
	"github.com/auroraride/aurservd/internal/ent/subscribe"
	"github.com/auroraride/aurservd/internal/ent/subscribereminder"
)

// SubscribeReminderQuery is the builder for querying SubscribeReminder entities.
type SubscribeReminderQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.SubscribeReminder
	// eager-loading edges.
	withSubscribe *SubscribeQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscribeReminderQuery builder.
func (srq *SubscribeReminderQuery) Where(ps ...predicate.SubscribeReminder) *SubscribeReminderQuery {
	srq.predicates = append(srq.predicates, ps...)
	return srq
}

// Limit adds a limit step to the query.
func (srq *SubscribeReminderQuery) Limit(limit int) *SubscribeReminderQuery {
	srq.limit = &limit
	return srq
}

// Offset adds an offset step to the query.
func (srq *SubscribeReminderQuery) Offset(offset int) *SubscribeReminderQuery {
	srq.offset = &offset
	return srq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (srq *SubscribeReminderQuery) Unique(unique bool) *SubscribeReminderQuery {
	srq.unique = &unique
	return srq
}

// Order adds an order step to the query.
func (srq *SubscribeReminderQuery) Order(o ...OrderFunc) *SubscribeReminderQuery {
	srq.order = append(srq.order, o...)
	return srq
}

// QuerySubscribe chains the current query on the "subscribe" edge.
func (srq *SubscribeReminderQuery) QuerySubscribe() *SubscribeQuery {
	query := &SubscribeQuery{config: srq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscribereminder.Table, subscribereminder.FieldID, selector),
			sqlgraph.To(subscribe.Table, subscribe.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, subscribereminder.SubscribeTable, subscribereminder.SubscribeColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubscribeReminder entity from the query.
// Returns a *NotFoundError when no SubscribeReminder was found.
func (srq *SubscribeReminderQuery) First(ctx context.Context) (*SubscribeReminder, error) {
	nodes, err := srq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscribereminder.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (srq *SubscribeReminderQuery) FirstX(ctx context.Context) *SubscribeReminder {
	node, err := srq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscribeReminder ID from the query.
// Returns a *NotFoundError when no SubscribeReminder ID was found.
func (srq *SubscribeReminderQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = srq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscribereminder.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (srq *SubscribeReminderQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := srq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscribeReminder entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscribeReminder entity is found.
// Returns a *NotFoundError when no SubscribeReminder entities are found.
func (srq *SubscribeReminderQuery) Only(ctx context.Context) (*SubscribeReminder, error) {
	nodes, err := srq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscribereminder.Label}
	default:
		return nil, &NotSingularError{subscribereminder.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (srq *SubscribeReminderQuery) OnlyX(ctx context.Context) *SubscribeReminder {
	node, err := srq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscribeReminder ID in the query.
// Returns a *NotSingularError when more than one SubscribeReminder ID is found.
// Returns a *NotFoundError when no entities are found.
func (srq *SubscribeReminderQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = srq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscribereminder.Label}
	default:
		err = &NotSingularError{subscribereminder.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (srq *SubscribeReminderQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := srq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscribeReminders.
func (srq *SubscribeReminderQuery) All(ctx context.Context) ([]*SubscribeReminder, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return srq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (srq *SubscribeReminderQuery) AllX(ctx context.Context) []*SubscribeReminder {
	nodes, err := srq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscribeReminder IDs.
func (srq *SubscribeReminderQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := srq.Select(subscribereminder.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (srq *SubscribeReminderQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := srq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (srq *SubscribeReminderQuery) Count(ctx context.Context) (int, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return srq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (srq *SubscribeReminderQuery) CountX(ctx context.Context) int {
	count, err := srq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (srq *SubscribeReminderQuery) Exist(ctx context.Context) (bool, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return srq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (srq *SubscribeReminderQuery) ExistX(ctx context.Context) bool {
	exist, err := srq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscribeReminderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (srq *SubscribeReminderQuery) Clone() *SubscribeReminderQuery {
	if srq == nil {
		return nil
	}
	return &SubscribeReminderQuery{
		config:        srq.config,
		limit:         srq.limit,
		offset:        srq.offset,
		order:         append([]OrderFunc{}, srq.order...),
		predicates:    append([]predicate.SubscribeReminder{}, srq.predicates...),
		withSubscribe: srq.withSubscribe.Clone(),
		// clone intermediate query.
		sql:    srq.sql.Clone(),
		path:   srq.path,
		unique: srq.unique,
	}
}

// WithSubscribe tells the query-builder to eager-load the nodes that are connected to
// the "subscribe" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *SubscribeReminderQuery) WithSubscribe(opts ...func(*SubscribeQuery)) *SubscribeReminderQuery {
	query := &SubscribeQuery{config: srq.config}
	for _, opt := range opts {
		opt(query)
	}
	srq.withSubscribe = query
	return srq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscribeReminder.Query().
//		GroupBy(subscribereminder.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (srq *SubscribeReminderQuery) GroupBy(field string, fields ...string) *SubscribeReminderGroupBy {
	grbuild := &SubscribeReminderGroupBy{config: srq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return srq.sqlQuery(ctx), nil
	}
	grbuild.label = subscribereminder.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SubscribeReminder.Query().
//		Select(subscribereminder.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (srq *SubscribeReminderQuery) Select(fields ...string) *SubscribeReminderSelect {
	srq.fields = append(srq.fields, fields...)
	selbuild := &SubscribeReminderSelect{SubscribeReminderQuery: srq}
	selbuild.label = subscribereminder.Label
	selbuild.flds, selbuild.scan = &srq.fields, selbuild.Scan
	return selbuild
}

func (srq *SubscribeReminderQuery) prepareQuery(ctx context.Context) error {
	for _, f := range srq.fields {
		if !subscribereminder.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if srq.path != nil {
		prev, err := srq.path(ctx)
		if err != nil {
			return err
		}
		srq.sql = prev
	}
	return nil
}

func (srq *SubscribeReminderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscribeReminder, error) {
	var (
		nodes       = []*SubscribeReminder{}
		_spec       = srq.querySpec()
		loadedTypes = [1]bool{
			srq.withSubscribe != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*SubscribeReminder).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &SubscribeReminder{config: srq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(srq.modifiers) > 0 {
		_spec.Modifiers = srq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, srq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := srq.withSubscribe; query != nil {
		ids := make([]uint64, 0, len(nodes))
		nodeids := make(map[uint64][]*SubscribeReminder)
		for i := range nodes {
			fk := nodes[i].SubscribeID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(subscribe.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "subscribe_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Subscribe = n
			}
		}
	}

	return nodes, nil
}

func (srq *SubscribeReminderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := srq.querySpec()
	if len(srq.modifiers) > 0 {
		_spec.Modifiers = srq.modifiers
	}
	_spec.Node.Columns = srq.fields
	if len(srq.fields) > 0 {
		_spec.Unique = srq.unique != nil && *srq.unique
	}
	return sqlgraph.CountNodes(ctx, srq.driver, _spec)
}

func (srq *SubscribeReminderQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := srq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (srq *SubscribeReminderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   subscribereminder.Table,
			Columns: subscribereminder.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: subscribereminder.FieldID,
			},
		},
		From:   srq.sql,
		Unique: true,
	}
	if unique := srq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := srq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscribereminder.FieldID)
		for i := range fields {
			if fields[i] != subscribereminder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := srq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := srq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := srq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := srq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (srq *SubscribeReminderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(srq.driver.Dialect())
	t1 := builder.Table(subscribereminder.Table)
	columns := srq.fields
	if len(columns) == 0 {
		columns = subscribereminder.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if srq.sql != nil {
		selector = srq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if srq.unique != nil && *srq.unique {
		selector.Distinct()
	}
	for _, m := range srq.modifiers {
		m(selector)
	}
	for _, p := range srq.predicates {
		p(selector)
	}
	for _, p := range srq.order {
		p(selector)
	}
	if offset := srq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := srq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (srq *SubscribeReminderQuery) Modify(modifiers ...func(s *sql.Selector)) *SubscribeReminderSelect {
	srq.modifiers = append(srq.modifiers, modifiers...)
	return srq.Select()
}

// SubscribeReminderGroupBy is the group-by builder for SubscribeReminder entities.
type SubscribeReminderGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srgb *SubscribeReminderGroupBy) Aggregate(fns ...AggregateFunc) *SubscribeReminderGroupBy {
	srgb.fns = append(srgb.fns, fns...)
	return srgb
}

// Scan applies the group-by query and scans the result into the given value.
func (srgb *SubscribeReminderGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := srgb.path(ctx)
	if err != nil {
		return err
	}
	srgb.sql = query
	return srgb.sqlScan(ctx, v)
}

func (srgb *SubscribeReminderGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range srgb.fields {
		if !subscribereminder.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := srgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (srgb *SubscribeReminderGroupBy) sqlQuery() *sql.Selector {
	selector := srgb.sql.Select()
	aggregation := make([]string, 0, len(srgb.fns))
	for _, fn := range srgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(srgb.fields)+len(srgb.fns))
		for _, f := range srgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(srgb.fields...)...)
}

// SubscribeReminderSelect is the builder for selecting fields of SubscribeReminder entities.
type SubscribeReminderSelect struct {
	*SubscribeReminderQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (srs *SubscribeReminderSelect) Scan(ctx context.Context, v interface{}) error {
	if err := srs.prepareQuery(ctx); err != nil {
		return err
	}
	srs.sql = srs.SubscribeReminderQuery.sqlQuery(ctx)
	return srs.sqlScan(ctx, v)
}

func (srs *SubscribeReminderSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := srs.sql.Query()
	if err := srs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (srs *SubscribeReminderSelect) Modify(modifiers ...func(s *sql.Selector)) *SubscribeReminderSelect {
	srs.modifiers = append(srs.modifiers, modifiers...)
	return srs
}
