// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contract is the predicate function for contract builders.
type Contract func(*sql.Selector)

// Manager is the predicate function for manager builders.
type Manager func(*sql.Selector)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)

// Rider is the predicate function for rider builders.
type Rider func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)
