// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/auroraride/aurservd/internal/ent/attendance"
	"github.com/auroraride/aurservd/internal/ent/batterymodel"
	"github.com/auroraride/aurservd/internal/ent/branch"
	"github.com/auroraride/aurservd/internal/ent/branchcontract"
	"github.com/auroraride/aurservd/internal/ent/business"
	"github.com/auroraride/aurservd/internal/ent/cabinet"
	"github.com/auroraride/aurservd/internal/ent/cabinetfault"
	"github.com/auroraride/aurservd/internal/ent/city"
	"github.com/auroraride/aurservd/internal/ent/commission"
	"github.com/auroraride/aurservd/internal/ent/contract"
	"github.com/auroraride/aurservd/internal/ent/employee"
	"github.com/auroraride/aurservd/internal/ent/enterprise"
	"github.com/auroraride/aurservd/internal/ent/enterprisebill"
	"github.com/auroraride/aurservd/internal/ent/enterprisecontract"
	"github.com/auroraride/aurservd/internal/ent/enterpriseprepayment"
	"github.com/auroraride/aurservd/internal/ent/enterpriseprice"
	"github.com/auroraride/aurservd/internal/ent/enterprisestatement"
	"github.com/auroraride/aurservd/internal/ent/enterprisestation"
	"github.com/auroraride/aurservd/internal/ent/exception"
	"github.com/auroraride/aurservd/internal/ent/exchange"
	"github.com/auroraride/aurservd/internal/ent/inventory"
	"github.com/auroraride/aurservd/internal/ent/manager"
	"github.com/auroraride/aurservd/internal/ent/order"
	"github.com/auroraride/aurservd/internal/ent/orderrefund"
	"github.com/auroraride/aurservd/internal/ent/person"
	"github.com/auroraride/aurservd/internal/ent/plan"
	"github.com/auroraride/aurservd/internal/ent/rider"
	"github.com/auroraride/aurservd/internal/ent/schema"
	"github.com/auroraride/aurservd/internal/ent/setting"
	"github.com/auroraride/aurservd/internal/ent/stock"
	"github.com/auroraride/aurservd/internal/ent/store"
	"github.com/auroraride/aurservd/internal/ent/subscribe"
	"github.com/auroraride/aurservd/internal/ent/subscribealter"
	"github.com/auroraride/aurservd/internal/ent/subscribepause"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attendanceMixin := schema.Attendance{}.Mixin()
	attendanceMixinHooks2 := attendanceMixin[2].Hooks()
	attendance.Hooks[0] = attendanceMixinHooks2[0]
	attendanceMixinFields0 := attendanceMixin[0].Fields()
	_ = attendanceMixinFields0
	attendanceFields := schema.Attendance{}.Fields()
	_ = attendanceFields
	// attendanceDescCreatedAt is the schema descriptor for created_at field.
	attendanceDescCreatedAt := attendanceMixinFields0[0].Descriptor()
	// attendance.DefaultCreatedAt holds the default value on creation for the created_at field.
	attendance.DefaultCreatedAt = attendanceDescCreatedAt.Default.(func() time.Time)
	// attendanceDescUpdatedAt is the schema descriptor for updated_at field.
	attendanceDescUpdatedAt := attendanceMixinFields0[1].Descriptor()
	// attendance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	attendance.DefaultUpdatedAt = attendanceDescUpdatedAt.Default.(func() time.Time)
	// attendance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	attendance.UpdateDefaultUpdatedAt = attendanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	batterymodelMixin := schema.BatteryModel{}.Mixin()
	batterymodelMixinHooks2 := batterymodelMixin[2].Hooks()
	batterymodel.Hooks[0] = batterymodelMixinHooks2[0]
	batterymodelMixinFields0 := batterymodelMixin[0].Fields()
	_ = batterymodelMixinFields0
	batterymodelFields := schema.BatteryModel{}.Fields()
	_ = batterymodelFields
	// batterymodelDescCreatedAt is the schema descriptor for created_at field.
	batterymodelDescCreatedAt := batterymodelMixinFields0[0].Descriptor()
	// batterymodel.DefaultCreatedAt holds the default value on creation for the created_at field.
	batterymodel.DefaultCreatedAt = batterymodelDescCreatedAt.Default.(func() time.Time)
	// batterymodelDescUpdatedAt is the schema descriptor for updated_at field.
	batterymodelDescUpdatedAt := batterymodelMixinFields0[1].Descriptor()
	// batterymodel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	batterymodel.DefaultUpdatedAt = batterymodelDescUpdatedAt.Default.(func() time.Time)
	// batterymodel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	batterymodel.UpdateDefaultUpdatedAt = batterymodelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// batterymodelDescEnable is the schema descriptor for enable field.
	batterymodelDescEnable := batterymodelFields[1].Descriptor()
	// batterymodel.DefaultEnable holds the default value on creation for the enable field.
	batterymodel.DefaultEnable = batterymodelDescEnable.Default.(bool)
	branchMixin := schema.Branch{}.Mixin()
	branchMixinHooks2 := branchMixin[2].Hooks()
	branch.Hooks[0] = branchMixinHooks2[0]
	branchMixinFields0 := branchMixin[0].Fields()
	_ = branchMixinFields0
	branchFields := schema.Branch{}.Fields()
	_ = branchFields
	// branchDescCreatedAt is the schema descriptor for created_at field.
	branchDescCreatedAt := branchMixinFields0[0].Descriptor()
	// branch.DefaultCreatedAt holds the default value on creation for the created_at field.
	branch.DefaultCreatedAt = branchDescCreatedAt.Default.(func() time.Time)
	// branchDescUpdatedAt is the schema descriptor for updated_at field.
	branchDescUpdatedAt := branchMixinFields0[1].Descriptor()
	// branch.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	branch.DefaultUpdatedAt = branchDescUpdatedAt.Default.(func() time.Time)
	// branch.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	branch.UpdateDefaultUpdatedAt = branchDescUpdatedAt.UpdateDefault.(func() time.Time)
	branchcontractMixin := schema.BranchContract{}.Mixin()
	branchcontractMixinHooks2 := branchcontractMixin[2].Hooks()
	branchcontract.Hooks[0] = branchcontractMixinHooks2[0]
	branchcontractMixinFields0 := branchcontractMixin[0].Fields()
	_ = branchcontractMixinFields0
	branchcontractFields := schema.BranchContract{}.Fields()
	_ = branchcontractFields
	// branchcontractDescCreatedAt is the schema descriptor for created_at field.
	branchcontractDescCreatedAt := branchcontractMixinFields0[0].Descriptor()
	// branchcontract.DefaultCreatedAt holds the default value on creation for the created_at field.
	branchcontract.DefaultCreatedAt = branchcontractDescCreatedAt.Default.(func() time.Time)
	// branchcontractDescUpdatedAt is the schema descriptor for updated_at field.
	branchcontractDescUpdatedAt := branchcontractMixinFields0[1].Descriptor()
	// branchcontract.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	branchcontract.DefaultUpdatedAt = branchcontractDescUpdatedAt.Default.(func() time.Time)
	// branchcontract.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	branchcontract.UpdateDefaultUpdatedAt = branchcontractDescUpdatedAt.UpdateDefault.(func() time.Time)
	businessMixin := schema.Business{}.Mixin()
	businessMixinHooks2 := businessMixin[2].Hooks()
	business.Hooks[0] = businessMixinHooks2[0]
	businessMixinFields0 := businessMixin[0].Fields()
	_ = businessMixinFields0
	businessFields := schema.Business{}.Fields()
	_ = businessFields
	// businessDescCreatedAt is the schema descriptor for created_at field.
	businessDescCreatedAt := businessMixinFields0[0].Descriptor()
	// business.DefaultCreatedAt holds the default value on creation for the created_at field.
	business.DefaultCreatedAt = businessDescCreatedAt.Default.(func() time.Time)
	// businessDescUpdatedAt is the schema descriptor for updated_at field.
	businessDescUpdatedAt := businessMixinFields0[1].Descriptor()
	// business.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	business.DefaultUpdatedAt = businessDescUpdatedAt.Default.(func() time.Time)
	// business.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	business.UpdateDefaultUpdatedAt = businessDescUpdatedAt.UpdateDefault.(func() time.Time)
	cabinetMixin := schema.Cabinet{}.Mixin()
	cabinetMixinHooks2 := cabinetMixin[2].Hooks()
	cabinet.Hooks[0] = cabinetMixinHooks2[0]
	cabinetMixinFields0 := cabinetMixin[0].Fields()
	_ = cabinetMixinFields0
	cabinetFields := schema.Cabinet{}.Fields()
	_ = cabinetFields
	// cabinetDescCreatedAt is the schema descriptor for created_at field.
	cabinetDescCreatedAt := cabinetMixinFields0[0].Descriptor()
	// cabinet.DefaultCreatedAt holds the default value on creation for the created_at field.
	cabinet.DefaultCreatedAt = cabinetDescCreatedAt.Default.(func() time.Time)
	// cabinetDescUpdatedAt is the schema descriptor for updated_at field.
	cabinetDescUpdatedAt := cabinetMixinFields0[1].Descriptor()
	// cabinet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cabinet.DefaultUpdatedAt = cabinetDescUpdatedAt.Default.(func() time.Time)
	// cabinet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cabinet.UpdateDefaultUpdatedAt = cabinetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cabinetDescHealth is the schema descriptor for health field.
	cabinetDescHealth := cabinetFields[7].Descriptor()
	// cabinet.DefaultHealth holds the default value on creation for the health field.
	cabinet.DefaultHealth = cabinetDescHealth.Default.(uint8)
	// cabinetDescBatteryNum is the schema descriptor for battery_num field.
	cabinetDescBatteryNum := cabinetFields[9].Descriptor()
	// cabinet.DefaultBatteryNum holds the default value on creation for the battery_num field.
	cabinet.DefaultBatteryNum = cabinetDescBatteryNum.Default.(uint)
	// cabinetDescBatteryFullNum is the schema descriptor for battery_full_num field.
	cabinetDescBatteryFullNum := cabinetFields[10].Descriptor()
	// cabinet.DefaultBatteryFullNum holds the default value on creation for the battery_full_num field.
	cabinet.DefaultBatteryFullNum = cabinetDescBatteryFullNum.Default.(uint)
	cabinetfaultMixin := schema.CabinetFault{}.Mixin()
	cabinetfaultMixinHooks2 := cabinetfaultMixin[2].Hooks()
	cabinetfault.Hooks[0] = cabinetfaultMixinHooks2[0]
	cabinetfaultMixinFields0 := cabinetfaultMixin[0].Fields()
	_ = cabinetfaultMixinFields0
	cabinetfaultFields := schema.CabinetFault{}.Fields()
	_ = cabinetfaultFields
	// cabinetfaultDescCreatedAt is the schema descriptor for created_at field.
	cabinetfaultDescCreatedAt := cabinetfaultMixinFields0[0].Descriptor()
	// cabinetfault.DefaultCreatedAt holds the default value on creation for the created_at field.
	cabinetfault.DefaultCreatedAt = cabinetfaultDescCreatedAt.Default.(func() time.Time)
	// cabinetfaultDescUpdatedAt is the schema descriptor for updated_at field.
	cabinetfaultDescUpdatedAt := cabinetfaultMixinFields0[1].Descriptor()
	// cabinetfault.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cabinetfault.DefaultUpdatedAt = cabinetfaultDescUpdatedAt.Default.(func() time.Time)
	// cabinetfault.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cabinetfault.UpdateDefaultUpdatedAt = cabinetfaultDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cabinetfaultDescStatus is the schema descriptor for status field.
	cabinetfaultDescStatus := cabinetfaultFields[0].Descriptor()
	// cabinetfault.DefaultStatus holds the default value on creation for the status field.
	cabinetfault.DefaultStatus = cabinetfaultDescStatus.Default.(uint8)
	cityMixin := schema.City{}.Mixin()
	cityMixinHooks2 := cityMixin[2].Hooks()
	city.Hooks[0] = cityMixinHooks2[0]
	cityMixinFields0 := cityMixin[0].Fields()
	_ = cityMixinFields0
	cityFields := schema.City{}.Fields()
	_ = cityFields
	// cityDescCreatedAt is the schema descriptor for created_at field.
	cityDescCreatedAt := cityMixinFields0[0].Descriptor()
	// city.DefaultCreatedAt holds the default value on creation for the created_at field.
	city.DefaultCreatedAt = cityDescCreatedAt.Default.(func() time.Time)
	// cityDescUpdatedAt is the schema descriptor for updated_at field.
	cityDescUpdatedAt := cityMixinFields0[1].Descriptor()
	// city.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	city.DefaultUpdatedAt = cityDescUpdatedAt.Default.(func() time.Time)
	// city.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	city.UpdateDefaultUpdatedAt = cityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cityDescName is the schema descriptor for name field.
	cityDescName := cityFields[2].Descriptor()
	// city.NameValidator is a validator for the "name" field. It is called by the builders before save.
	city.NameValidator = cityDescName.Validators[0].(func(string) error)
	// cityDescCode is the schema descriptor for code field.
	cityDescCode := cityFields[3].Descriptor()
	// city.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	city.CodeValidator = cityDescCode.Validators[0].(func(string) error)
	commissionMixin := schema.Commission{}.Mixin()
	commissionMixinHooks2 := commissionMixin[2].Hooks()
	commission.Hooks[0] = commissionMixinHooks2[0]
	commissionMixinFields0 := commissionMixin[0].Fields()
	_ = commissionMixinFields0
	commissionFields := schema.Commission{}.Fields()
	_ = commissionFields
	// commissionDescCreatedAt is the schema descriptor for created_at field.
	commissionDescCreatedAt := commissionMixinFields0[0].Descriptor()
	// commission.DefaultCreatedAt holds the default value on creation for the created_at field.
	commission.DefaultCreatedAt = commissionDescCreatedAt.Default.(func() time.Time)
	// commissionDescUpdatedAt is the schema descriptor for updated_at field.
	commissionDescUpdatedAt := commissionMixinFields0[1].Descriptor()
	// commission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	commission.DefaultUpdatedAt = commissionDescUpdatedAt.Default.(func() time.Time)
	// commission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	commission.UpdateDefaultUpdatedAt = commissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commissionDescStatus is the schema descriptor for status field.
	commissionDescStatus := commissionFields[2].Descriptor()
	// commission.DefaultStatus holds the default value on creation for the status field.
	commission.DefaultStatus = commissionDescStatus.Default.(uint8)
	contractMixin := schema.Contract{}.Mixin()
	contractMixinHooks2 := contractMixin[2].Hooks()
	contract.Hooks[0] = contractMixinHooks2[0]
	contractMixinFields0 := contractMixin[0].Fields()
	_ = contractMixinFields0
	contractFields := schema.Contract{}.Fields()
	_ = contractFields
	// contractDescCreatedAt is the schema descriptor for created_at field.
	contractDescCreatedAt := contractMixinFields0[0].Descriptor()
	// contract.DefaultCreatedAt holds the default value on creation for the created_at field.
	contract.DefaultCreatedAt = contractDescCreatedAt.Default.(func() time.Time)
	// contractDescUpdatedAt is the schema descriptor for updated_at field.
	contractDescUpdatedAt := contractMixinFields0[1].Descriptor()
	// contract.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	contract.DefaultUpdatedAt = contractDescUpdatedAt.Default.(func() time.Time)
	// contract.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	contract.UpdateDefaultUpdatedAt = contractDescUpdatedAt.UpdateDefault.(func() time.Time)
	// contractDescStatus is the schema descriptor for status field.
	contractDescStatus := contractFields[0].Descriptor()
	// contract.DefaultStatus holds the default value on creation for the status field.
	contract.DefaultStatus = contractDescStatus.Default.(uint8)
	// contractDescFlowID is the schema descriptor for flow_id field.
	contractDescFlowID := contractFields[2].Descriptor()
	// contract.FlowIDValidator is a validator for the "flow_id" field. It is called by the builders before save.
	contract.FlowIDValidator = func() func(string) error {
		validators := contractDescFlowID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(flow_id string) error {
			for _, fn := range fns {
				if err := fn(flow_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// contractDescSn is the schema descriptor for sn field.
	contractDescSn := contractFields[3].Descriptor()
	// contract.SnValidator is a validator for the "sn" field. It is called by the builders before save.
	contract.SnValidator = func() func(string) error {
		validators := contractDescSn.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(sn string) error {
			for _, fn := range fns {
				if err := fn(sn); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// contractDescEffective is the schema descriptor for effective field.
	contractDescEffective := contractFields[5].Descriptor()
	// contract.DefaultEffective holds the default value on creation for the effective field.
	contract.DefaultEffective = contractDescEffective.Default.(bool)
	employeeMixin := schema.Employee{}.Mixin()
	employeeMixinHooks2 := employeeMixin[2].Hooks()
	employee.Hooks[0] = employeeMixinHooks2[0]
	employeeMixinFields0 := employeeMixin[0].Fields()
	_ = employeeMixinFields0
	employeeFields := schema.Employee{}.Fields()
	_ = employeeFields
	// employeeDescCreatedAt is the schema descriptor for created_at field.
	employeeDescCreatedAt := employeeMixinFields0[0].Descriptor()
	// employee.DefaultCreatedAt holds the default value on creation for the created_at field.
	employee.DefaultCreatedAt = employeeDescCreatedAt.Default.(func() time.Time)
	// employeeDescUpdatedAt is the schema descriptor for updated_at field.
	employeeDescUpdatedAt := employeeMixinFields0[1].Descriptor()
	// employee.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employee.DefaultUpdatedAt = employeeDescUpdatedAt.Default.(func() time.Time)
	// employee.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	employee.UpdateDefaultUpdatedAt = employeeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// employeeDescEnable is the schema descriptor for enable field.
	employeeDescEnable := employeeFields[3].Descriptor()
	// employee.DefaultEnable holds the default value on creation for the enable field.
	employee.DefaultEnable = employeeDescEnable.Default.(bool)
	enterpriseMixin := schema.Enterprise{}.Mixin()
	enterpriseMixinHooks2 := enterpriseMixin[2].Hooks()
	enterprise.Hooks[0] = enterpriseMixinHooks2[0]
	enterpriseMixinFields0 := enterpriseMixin[0].Fields()
	_ = enterpriseMixinFields0
	enterpriseFields := schema.Enterprise{}.Fields()
	_ = enterpriseFields
	// enterpriseDescCreatedAt is the schema descriptor for created_at field.
	enterpriseDescCreatedAt := enterpriseMixinFields0[0].Descriptor()
	// enterprise.DefaultCreatedAt holds the default value on creation for the created_at field.
	enterprise.DefaultCreatedAt = enterpriseDescCreatedAt.Default.(func() time.Time)
	// enterpriseDescUpdatedAt is the schema descriptor for updated_at field.
	enterpriseDescUpdatedAt := enterpriseMixinFields0[1].Descriptor()
	// enterprise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	enterprise.DefaultUpdatedAt = enterpriseDescUpdatedAt.Default.(func() time.Time)
	// enterprise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	enterprise.UpdateDefaultUpdatedAt = enterpriseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// enterpriseDescDeposit is the schema descriptor for deposit field.
	enterpriseDescDeposit := enterpriseFields[7].Descriptor()
	// enterprise.DefaultDeposit holds the default value on creation for the deposit field.
	enterprise.DefaultDeposit = enterpriseDescDeposit.Default.(float64)
	// enterpriseDescBalance is the schema descriptor for balance field.
	enterpriseDescBalance := enterpriseFields[8].Descriptor()
	// enterprise.DefaultBalance holds the default value on creation for the balance field.
	enterprise.DefaultBalance = enterpriseDescBalance.Default.(float64)
	enterprisebillMixin := schema.EnterpriseBill{}.Mixin()
	enterprisebillMixinHooks2 := enterprisebillMixin[2].Hooks()
	enterprisebill.Hooks[0] = enterprisebillMixinHooks2[0]
	enterprisebillMixinFields0 := enterprisebillMixin[0].Fields()
	_ = enterprisebillMixinFields0
	enterprisebillFields := schema.EnterpriseBill{}.Fields()
	_ = enterprisebillFields
	// enterprisebillDescCreatedAt is the schema descriptor for created_at field.
	enterprisebillDescCreatedAt := enterprisebillMixinFields0[0].Descriptor()
	// enterprisebill.DefaultCreatedAt holds the default value on creation for the created_at field.
	enterprisebill.DefaultCreatedAt = enterprisebillDescCreatedAt.Default.(func() time.Time)
	// enterprisebillDescUpdatedAt is the schema descriptor for updated_at field.
	enterprisebillDescUpdatedAt := enterprisebillMixinFields0[1].Descriptor()
	// enterprisebill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	enterprisebill.DefaultUpdatedAt = enterprisebillDescUpdatedAt.Default.(func() time.Time)
	// enterprisebill.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	enterprisebill.UpdateDefaultUpdatedAt = enterprisebillDescUpdatedAt.UpdateDefault.(func() time.Time)
	enterprisecontractMixin := schema.EnterpriseContract{}.Mixin()
	enterprisecontractMixinHooks2 := enterprisecontractMixin[2].Hooks()
	enterprisecontract.Hooks[0] = enterprisecontractMixinHooks2[0]
	enterprisecontractMixinFields0 := enterprisecontractMixin[0].Fields()
	_ = enterprisecontractMixinFields0
	enterprisecontractFields := schema.EnterpriseContract{}.Fields()
	_ = enterprisecontractFields
	// enterprisecontractDescCreatedAt is the schema descriptor for created_at field.
	enterprisecontractDescCreatedAt := enterprisecontractMixinFields0[0].Descriptor()
	// enterprisecontract.DefaultCreatedAt holds the default value on creation for the created_at field.
	enterprisecontract.DefaultCreatedAt = enterprisecontractDescCreatedAt.Default.(func() time.Time)
	// enterprisecontractDescUpdatedAt is the schema descriptor for updated_at field.
	enterprisecontractDescUpdatedAt := enterprisecontractMixinFields0[1].Descriptor()
	// enterprisecontract.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	enterprisecontract.DefaultUpdatedAt = enterprisecontractDescUpdatedAt.Default.(func() time.Time)
	// enterprisecontract.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	enterprisecontract.UpdateDefaultUpdatedAt = enterprisecontractDescUpdatedAt.UpdateDefault.(func() time.Time)
	enterpriseprepaymentMixin := schema.EnterprisePrepayment{}.Mixin()
	enterpriseprepaymentMixinHooks2 := enterpriseprepaymentMixin[2].Hooks()
	enterpriseprepayment.Hooks[0] = enterpriseprepaymentMixinHooks2[0]
	enterpriseprepaymentMixinFields0 := enterpriseprepaymentMixin[0].Fields()
	_ = enterpriseprepaymentMixinFields0
	enterpriseprepaymentFields := schema.EnterprisePrepayment{}.Fields()
	_ = enterpriseprepaymentFields
	// enterpriseprepaymentDescCreatedAt is the schema descriptor for created_at field.
	enterpriseprepaymentDescCreatedAt := enterpriseprepaymentMixinFields0[0].Descriptor()
	// enterpriseprepayment.DefaultCreatedAt holds the default value on creation for the created_at field.
	enterpriseprepayment.DefaultCreatedAt = enterpriseprepaymentDescCreatedAt.Default.(func() time.Time)
	// enterpriseprepaymentDescUpdatedAt is the schema descriptor for updated_at field.
	enterpriseprepaymentDescUpdatedAt := enterpriseprepaymentMixinFields0[1].Descriptor()
	// enterpriseprepayment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	enterpriseprepayment.DefaultUpdatedAt = enterpriseprepaymentDescUpdatedAt.Default.(func() time.Time)
	// enterpriseprepayment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	enterpriseprepayment.UpdateDefaultUpdatedAt = enterpriseprepaymentDescUpdatedAt.UpdateDefault.(func() time.Time)
	enterprisepriceMixin := schema.EnterprisePrice{}.Mixin()
	enterprisepriceMixinHooks2 := enterprisepriceMixin[2].Hooks()
	enterpriseprice.Hooks[0] = enterprisepriceMixinHooks2[0]
	enterprisepriceMixinFields0 := enterprisepriceMixin[0].Fields()
	_ = enterprisepriceMixinFields0
	enterprisepriceFields := schema.EnterprisePrice{}.Fields()
	_ = enterprisepriceFields
	// enterprisepriceDescCreatedAt is the schema descriptor for created_at field.
	enterprisepriceDescCreatedAt := enterprisepriceMixinFields0[0].Descriptor()
	// enterpriseprice.DefaultCreatedAt holds the default value on creation for the created_at field.
	enterpriseprice.DefaultCreatedAt = enterprisepriceDescCreatedAt.Default.(func() time.Time)
	// enterprisepriceDescUpdatedAt is the schema descriptor for updated_at field.
	enterprisepriceDescUpdatedAt := enterprisepriceMixinFields0[1].Descriptor()
	// enterpriseprice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	enterpriseprice.DefaultUpdatedAt = enterprisepriceDescUpdatedAt.Default.(func() time.Time)
	// enterpriseprice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	enterpriseprice.UpdateDefaultUpdatedAt = enterprisepriceDescUpdatedAt.UpdateDefault.(func() time.Time)
	enterprisestatementMixin := schema.EnterpriseStatement{}.Mixin()
	enterprisestatementMixinHooks2 := enterprisestatementMixin[2].Hooks()
	enterprisestatement.Hooks[0] = enterprisestatementMixinHooks2[0]
	enterprisestatementMixinFields0 := enterprisestatementMixin[0].Fields()
	_ = enterprisestatementMixinFields0
	enterprisestatementFields := schema.EnterpriseStatement{}.Fields()
	_ = enterprisestatementFields
	// enterprisestatementDescCreatedAt is the schema descriptor for created_at field.
	enterprisestatementDescCreatedAt := enterprisestatementMixinFields0[0].Descriptor()
	// enterprisestatement.DefaultCreatedAt holds the default value on creation for the created_at field.
	enterprisestatement.DefaultCreatedAt = enterprisestatementDescCreatedAt.Default.(func() time.Time)
	// enterprisestatementDescUpdatedAt is the schema descriptor for updated_at field.
	enterprisestatementDescUpdatedAt := enterprisestatementMixinFields0[1].Descriptor()
	// enterprisestatement.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	enterprisestatement.DefaultUpdatedAt = enterprisestatementDescUpdatedAt.Default.(func() time.Time)
	// enterprisestatement.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	enterprisestatement.UpdateDefaultUpdatedAt = enterprisestatementDescUpdatedAt.UpdateDefault.(func() time.Time)
	// enterprisestatementDescCost is the schema descriptor for cost field.
	enterprisestatementDescCost := enterprisestatementFields[1].Descriptor()
	// enterprisestatement.DefaultCost holds the default value on creation for the cost field.
	enterprisestatement.DefaultCost = enterprisestatementDescCost.Default.(float64)
	// enterprisestatementDescBalance is the schema descriptor for balance field.
	enterprisestatementDescBalance := enterprisestatementFields[2].Descriptor()
	// enterprisestatement.DefaultBalance holds the default value on creation for the balance field.
	enterprisestatement.DefaultBalance = enterprisestatementDescBalance.Default.(float64)
	// enterprisestatementDescDays is the schema descriptor for days field.
	enterprisestatementDescDays := enterprisestatementFields[4].Descriptor()
	// enterprisestatement.DefaultDays holds the default value on creation for the days field.
	enterprisestatement.DefaultDays = enterprisestatementDescDays.Default.(int)
	// enterprisestatementDescRiderNumber is the schema descriptor for rider_number field.
	enterprisestatementDescRiderNumber := enterprisestatementFields[5].Descriptor()
	// enterprisestatement.DefaultRiderNumber holds the default value on creation for the rider_number field.
	enterprisestatement.DefaultRiderNumber = enterprisestatementDescRiderNumber.Default.(int)
	enterprisestationMixin := schema.EnterpriseStation{}.Mixin()
	enterprisestationMixinHooks2 := enterprisestationMixin[2].Hooks()
	enterprisestation.Hooks[0] = enterprisestationMixinHooks2[0]
	enterprisestationMixinFields0 := enterprisestationMixin[0].Fields()
	_ = enterprisestationMixinFields0
	enterprisestationFields := schema.EnterpriseStation{}.Fields()
	_ = enterprisestationFields
	// enterprisestationDescCreatedAt is the schema descriptor for created_at field.
	enterprisestationDescCreatedAt := enterprisestationMixinFields0[0].Descriptor()
	// enterprisestation.DefaultCreatedAt holds the default value on creation for the created_at field.
	enterprisestation.DefaultCreatedAt = enterprisestationDescCreatedAt.Default.(func() time.Time)
	// enterprisestationDescUpdatedAt is the schema descriptor for updated_at field.
	enterprisestationDescUpdatedAt := enterprisestationMixinFields0[1].Descriptor()
	// enterprisestation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	enterprisestation.DefaultUpdatedAt = enterprisestationDescUpdatedAt.Default.(func() time.Time)
	// enterprisestation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	enterprisestation.UpdateDefaultUpdatedAt = enterprisestationDescUpdatedAt.UpdateDefault.(func() time.Time)
	exceptionMixin := schema.Exception{}.Mixin()
	exceptionMixinHooks2 := exceptionMixin[2].Hooks()
	exception.Hooks[0] = exceptionMixinHooks2[0]
	exceptionMixinFields0 := exceptionMixin[0].Fields()
	_ = exceptionMixinFields0
	exceptionFields := schema.Exception{}.Fields()
	_ = exceptionFields
	// exceptionDescCreatedAt is the schema descriptor for created_at field.
	exceptionDescCreatedAt := exceptionMixinFields0[0].Descriptor()
	// exception.DefaultCreatedAt holds the default value on creation for the created_at field.
	exception.DefaultCreatedAt = exceptionDescCreatedAt.Default.(func() time.Time)
	// exceptionDescUpdatedAt is the schema descriptor for updated_at field.
	exceptionDescUpdatedAt := exceptionMixinFields0[1].Descriptor()
	// exception.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exception.DefaultUpdatedAt = exceptionDescUpdatedAt.Default.(func() time.Time)
	// exception.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exception.UpdateDefaultUpdatedAt = exceptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exceptionDescStatus is the schema descriptor for status field.
	exceptionDescStatus := exceptionFields[0].Descriptor()
	// exception.DefaultStatus holds the default value on creation for the status field.
	exception.DefaultStatus = exceptionDescStatus.Default.(uint8)
	exchangeMixin := schema.Exchange{}.Mixin()
	exchangeMixinHooks2 := exchangeMixin[2].Hooks()
	exchange.Hooks[0] = exchangeMixinHooks2[0]
	exchangeMixinFields0 := exchangeMixin[0].Fields()
	_ = exchangeMixinFields0
	exchangeFields := schema.Exchange{}.Fields()
	_ = exchangeFields
	// exchangeDescCreatedAt is the schema descriptor for created_at field.
	exchangeDescCreatedAt := exchangeMixinFields0[0].Descriptor()
	// exchange.DefaultCreatedAt holds the default value on creation for the created_at field.
	exchange.DefaultCreatedAt = exchangeDescCreatedAt.Default.(func() time.Time)
	// exchangeDescUpdatedAt is the schema descriptor for updated_at field.
	exchangeDescUpdatedAt := exchangeMixinFields0[1].Descriptor()
	// exchange.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exchange.DefaultUpdatedAt = exchangeDescUpdatedAt.Default.(func() time.Time)
	// exchange.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exchange.UpdateDefaultUpdatedAt = exchangeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exchangeDescSuccess is the schema descriptor for success field.
	exchangeDescSuccess := exchangeFields[4].Descriptor()
	// exchange.DefaultSuccess holds the default value on creation for the success field.
	exchange.DefaultSuccess = exchangeDescSuccess.Default.(bool)
	inventoryMixin := schema.Inventory{}.Mixin()
	inventoryMixinHooks2 := inventoryMixin[2].Hooks()
	inventory.Hooks[0] = inventoryMixinHooks2[0]
	inventoryMixinFields0 := inventoryMixin[0].Fields()
	_ = inventoryMixinFields0
	inventoryFields := schema.Inventory{}.Fields()
	_ = inventoryFields
	// inventoryDescCreatedAt is the schema descriptor for created_at field.
	inventoryDescCreatedAt := inventoryMixinFields0[0].Descriptor()
	// inventory.DefaultCreatedAt holds the default value on creation for the created_at field.
	inventory.DefaultCreatedAt = inventoryDescCreatedAt.Default.(func() time.Time)
	// inventoryDescUpdatedAt is the schema descriptor for updated_at field.
	inventoryDescUpdatedAt := inventoryMixinFields0[1].Descriptor()
	// inventory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	inventory.DefaultUpdatedAt = inventoryDescUpdatedAt.Default.(func() time.Time)
	// inventory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	inventory.UpdateDefaultUpdatedAt = inventoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	managerMixin := schema.Manager{}.Mixin()
	managerMixinHooks2 := managerMixin[2].Hooks()
	manager.Hooks[0] = managerMixinHooks2[0]
	managerMixinFields0 := managerMixin[0].Fields()
	_ = managerMixinFields0
	managerFields := schema.Manager{}.Fields()
	_ = managerFields
	// managerDescCreatedAt is the schema descriptor for created_at field.
	managerDescCreatedAt := managerMixinFields0[0].Descriptor()
	// manager.DefaultCreatedAt holds the default value on creation for the created_at field.
	manager.DefaultCreatedAt = managerDescCreatedAt.Default.(func() time.Time)
	// managerDescUpdatedAt is the schema descriptor for updated_at field.
	managerDescUpdatedAt := managerMixinFields0[1].Descriptor()
	// manager.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	manager.DefaultUpdatedAt = managerDescUpdatedAt.Default.(func() time.Time)
	// manager.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	manager.UpdateDefaultUpdatedAt = managerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// managerDescPhone is the schema descriptor for phone field.
	managerDescPhone := managerFields[0].Descriptor()
	// manager.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	manager.PhoneValidator = managerDescPhone.Validators[0].(func(string) error)
	// managerDescName is the schema descriptor for name field.
	managerDescName := managerFields[1].Descriptor()
	// manager.NameValidator is a validator for the "name" field. It is called by the builders before save.
	manager.NameValidator = managerDescName.Validators[0].(func(string) error)
	orderMixin := schema.Order{}.Mixin()
	orderMixinHooks2 := orderMixin[2].Hooks()
	order.Hooks[0] = orderMixinHooks2[0]
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderMixinFields0[0].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[3].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(uint8)
	// orderDescTotal is the schema descriptor for total field.
	orderDescTotal := orderFields[9].Descriptor()
	// order.DefaultTotal holds the default value on creation for the total field.
	order.DefaultTotal = orderDescTotal.Default.(float64)
	orderrefundMixin := schema.OrderRefund{}.Mixin()
	orderrefundMixinHooks2 := orderrefundMixin[2].Hooks()
	orderrefund.Hooks[0] = orderrefundMixinHooks2[0]
	orderrefundMixinFields0 := orderrefundMixin[0].Fields()
	_ = orderrefundMixinFields0
	orderrefundFields := schema.OrderRefund{}.Fields()
	_ = orderrefundFields
	// orderrefundDescCreatedAt is the schema descriptor for created_at field.
	orderrefundDescCreatedAt := orderrefundMixinFields0[0].Descriptor()
	// orderrefund.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderrefund.DefaultCreatedAt = orderrefundDescCreatedAt.Default.(func() time.Time)
	// orderrefundDescUpdatedAt is the schema descriptor for updated_at field.
	orderrefundDescUpdatedAt := orderrefundMixinFields0[1].Descriptor()
	// orderrefund.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderrefund.DefaultUpdatedAt = orderrefundDescUpdatedAt.Default.(func() time.Time)
	// orderrefund.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderrefund.UpdateDefaultUpdatedAt = orderrefundDescUpdatedAt.UpdateDefault.(func() time.Time)
	personMixin := schema.Person{}.Mixin()
	personMixinHooks2 := personMixin[2].Hooks()
	person.Hooks[0] = personMixinHooks2[0]
	personMixinFields0 := personMixin[0].Fields()
	_ = personMixinFields0
	personFields := schema.Person{}.Fields()
	_ = personFields
	// personDescCreatedAt is the schema descriptor for created_at field.
	personDescCreatedAt := personMixinFields0[0].Descriptor()
	// person.DefaultCreatedAt holds the default value on creation for the created_at field.
	person.DefaultCreatedAt = personDescCreatedAt.Default.(func() time.Time)
	// personDescUpdatedAt is the schema descriptor for updated_at field.
	personDescUpdatedAt := personMixinFields0[1].Descriptor()
	// person.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	person.DefaultUpdatedAt = personDescUpdatedAt.Default.(func() time.Time)
	// person.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	person.UpdateDefaultUpdatedAt = personDescUpdatedAt.UpdateDefault.(func() time.Time)
	// personDescStatus is the schema descriptor for status field.
	personDescStatus := personFields[0].Descriptor()
	// person.DefaultStatus holds the default value on creation for the status field.
	person.DefaultStatus = personDescStatus.Default.(uint8)
	// personDescBanned is the schema descriptor for banned field.
	personDescBanned := personFields[1].Descriptor()
	// person.DefaultBanned holds the default value on creation for the banned field.
	person.DefaultBanned = personDescBanned.Default.(bool)
	// personDescName is the schema descriptor for name field.
	personDescName := personFields[2].Descriptor()
	// person.NameValidator is a validator for the "name" field. It is called by the builders before save.
	person.NameValidator = personDescName.Validators[0].(func(string) error)
	// personDescIDCardNumber is the schema descriptor for id_card_number field.
	personDescIDCardNumber := personFields[3].Descriptor()
	// person.IDCardNumberValidator is a validator for the "id_card_number" field. It is called by the builders before save.
	person.IDCardNumberValidator = personDescIDCardNumber.Validators[0].(func(string) error)
	// personDescIDCardType is the schema descriptor for id_card_type field.
	personDescIDCardType := personFields[4].Descriptor()
	// person.DefaultIDCardType holds the default value on creation for the id_card_type field.
	person.DefaultIDCardType = personDescIDCardType.Default.(uint8)
	planMixin := schema.Plan{}.Mixin()
	planMixinHooks2 := planMixin[2].Hooks()
	plan.Hooks[0] = planMixinHooks2[0]
	planMixinFields0 := planMixin[0].Fields()
	_ = planMixinFields0
	planFields := schema.Plan{}.Fields()
	_ = planFields
	// planDescCreatedAt is the schema descriptor for created_at field.
	planDescCreatedAt := planMixinFields0[0].Descriptor()
	// plan.DefaultCreatedAt holds the default value on creation for the created_at field.
	plan.DefaultCreatedAt = planDescCreatedAt.Default.(func() time.Time)
	// planDescUpdatedAt is the schema descriptor for updated_at field.
	planDescUpdatedAt := planMixinFields0[1].Descriptor()
	// plan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plan.DefaultUpdatedAt = planDescUpdatedAt.Default.(func() time.Time)
	// plan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plan.UpdateDefaultUpdatedAt = planDescUpdatedAt.UpdateDefault.(func() time.Time)
	riderMixin := schema.Rider{}.Mixin()
	riderMixinHooks2 := riderMixin[2].Hooks()
	rider.Hooks[0] = riderMixinHooks2[0]
	riderMixinFields0 := riderMixin[0].Fields()
	_ = riderMixinFields0
	riderFields := schema.Rider{}.Fields()
	_ = riderFields
	// riderDescCreatedAt is the schema descriptor for created_at field.
	riderDescCreatedAt := riderMixinFields0[0].Descriptor()
	// rider.DefaultCreatedAt holds the default value on creation for the created_at field.
	rider.DefaultCreatedAt = riderDescCreatedAt.Default.(func() time.Time)
	// riderDescUpdatedAt is the schema descriptor for updated_at field.
	riderDescUpdatedAt := riderMixinFields0[1].Descriptor()
	// rider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rider.DefaultUpdatedAt = riderDescUpdatedAt.Default.(func() time.Time)
	// rider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rider.UpdateDefaultUpdatedAt = riderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// riderDescPhone is the schema descriptor for phone field.
	riderDescPhone := riderFields[2].Descriptor()
	// rider.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	rider.PhoneValidator = riderDescPhone.Validators[0].(func(string) error)
	// riderDescLastDevice is the schema descriptor for last_device field.
	riderDescLastDevice := riderFields[5].Descriptor()
	// rider.LastDeviceValidator is a validator for the "last_device" field. It is called by the builders before save.
	rider.LastDeviceValidator = riderDescLastDevice.Validators[0].(func(string) error)
	// riderDescIsNewDevice is the schema descriptor for is_new_device field.
	riderDescIsNewDevice := riderFields[6].Descriptor()
	// rider.DefaultIsNewDevice holds the default value on creation for the is_new_device field.
	rider.DefaultIsNewDevice = riderDescIsNewDevice.Default.(bool)
	// riderDescPushID is the schema descriptor for push_id field.
	riderDescPushID := riderFields[8].Descriptor()
	// rider.PushIDValidator is a validator for the "push_id" field. It is called by the builders before save.
	rider.PushIDValidator = riderDescPushID.Validators[0].(func(string) error)
	// riderDescBlocked is the schema descriptor for blocked field.
	riderDescBlocked := riderFields[12].Descriptor()
	// rider.DefaultBlocked holds the default value on creation for the blocked field.
	rider.DefaultBlocked = riderDescBlocked.Default.(bool)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinHooks1 := settingMixin[1].Hooks()
	setting.Hooks[0] = settingMixinHooks1[0]
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
	stockMixin := schema.Stock{}.Mixin()
	stockMixinHooks2 := stockMixin[2].Hooks()
	stockHooks := schema.Stock{}.Hooks()
	stock.Hooks[0] = stockMixinHooks2[0]
	stock.Hooks[1] = stockHooks[0]
	stockMixinFields0 := stockMixin[0].Fields()
	_ = stockMixinFields0
	stockFields := schema.Stock{}.Fields()
	_ = stockFields
	// stockDescCreatedAt is the schema descriptor for created_at field.
	stockDescCreatedAt := stockMixinFields0[0].Descriptor()
	// stock.DefaultCreatedAt holds the default value on creation for the created_at field.
	stock.DefaultCreatedAt = stockDescCreatedAt.Default.(func() time.Time)
	// stockDescUpdatedAt is the schema descriptor for updated_at field.
	stockDescUpdatedAt := stockMixinFields0[1].Descriptor()
	// stock.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	stock.DefaultUpdatedAt = stockDescUpdatedAt.Default.(func() time.Time)
	// stock.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	stock.UpdateDefaultUpdatedAt = stockDescUpdatedAt.UpdateDefault.(func() time.Time)
	// stockDescType is the schema descriptor for type field.
	stockDescType := stockFields[1].Descriptor()
	// stock.DefaultType holds the default value on creation for the type field.
	stock.DefaultType = stockDescType.Default.(uint8)
	storeMixin := schema.Store{}.Mixin()
	storeMixinHooks2 := storeMixin[2].Hooks()
	store.Hooks[0] = storeMixinHooks2[0]
	storeMixinFields0 := storeMixin[0].Fields()
	_ = storeMixinFields0
	storeFields := schema.Store{}.Fields()
	_ = storeFields
	// storeDescCreatedAt is the schema descriptor for created_at field.
	storeDescCreatedAt := storeMixinFields0[0].Descriptor()
	// store.DefaultCreatedAt holds the default value on creation for the created_at field.
	store.DefaultCreatedAt = storeDescCreatedAt.Default.(func() time.Time)
	// storeDescUpdatedAt is the schema descriptor for updated_at field.
	storeDescUpdatedAt := storeMixinFields0[1].Descriptor()
	// store.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	store.DefaultUpdatedAt = storeDescUpdatedAt.Default.(func() time.Time)
	// store.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	store.UpdateDefaultUpdatedAt = storeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// storeDescStatus is the schema descriptor for status field.
	storeDescStatus := storeFields[4].Descriptor()
	// store.DefaultStatus holds the default value on creation for the status field.
	store.DefaultStatus = storeDescStatus.Default.(uint8)
	subscribeMixin := schema.Subscribe{}.Mixin()
	subscribeMixinHooks2 := subscribeMixin[2].Hooks()
	subscribeHooks := schema.Subscribe{}.Hooks()
	subscribe.Hooks[0] = subscribeMixinHooks2[0]
	subscribe.Hooks[1] = subscribeHooks[0]
	subscribeMixinFields0 := subscribeMixin[0].Fields()
	_ = subscribeMixinFields0
	subscribeFields := schema.Subscribe{}.Fields()
	_ = subscribeFields
	// subscribeDescCreatedAt is the schema descriptor for created_at field.
	subscribeDescCreatedAt := subscribeMixinFields0[0].Descriptor()
	// subscribe.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscribe.DefaultCreatedAt = subscribeDescCreatedAt.Default.(func() time.Time)
	// subscribeDescUpdatedAt is the schema descriptor for updated_at field.
	subscribeDescUpdatedAt := subscribeMixinFields0[1].Descriptor()
	// subscribe.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscribe.DefaultUpdatedAt = subscribeDescUpdatedAt.Default.(func() time.Time)
	// subscribe.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscribe.UpdateDefaultUpdatedAt = subscribeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subscribeDescStatus is the schema descriptor for status field.
	subscribeDescStatus := subscribeFields[3].Descriptor()
	// subscribe.DefaultStatus holds the default value on creation for the status field.
	subscribe.DefaultStatus = subscribeDescStatus.Default.(uint8)
	// subscribeDescType is the schema descriptor for type field.
	subscribeDescType := subscribeFields[4].Descriptor()
	// subscribe.DefaultType holds the default value on creation for the type field.
	subscribe.DefaultType = subscribeDescType.Default.(uint)
	// subscribeDescAlterDays is the schema descriptor for alter_days field.
	subscribeDescAlterDays := subscribeFields[7].Descriptor()
	// subscribe.DefaultAlterDays holds the default value on creation for the alter_days field.
	subscribe.DefaultAlterDays = subscribeDescAlterDays.Default.(int)
	// subscribeDescPauseDays is the schema descriptor for pause_days field.
	subscribeDescPauseDays := subscribeFields[8].Descriptor()
	// subscribe.DefaultPauseDays holds the default value on creation for the pause_days field.
	subscribe.DefaultPauseDays = subscribeDescPauseDays.Default.(int)
	// subscribeDescRenewalDays is the schema descriptor for renewal_days field.
	subscribeDescRenewalDays := subscribeFields[9].Descriptor()
	// subscribe.DefaultRenewalDays holds the default value on creation for the renewal_days field.
	subscribe.DefaultRenewalDays = subscribeDescRenewalDays.Default.(int)
	// subscribeDescOverdueDays is the schema descriptor for overdue_days field.
	subscribeDescOverdueDays := subscribeFields[10].Descriptor()
	// subscribe.DefaultOverdueDays holds the default value on creation for the overdue_days field.
	subscribe.DefaultOverdueDays = subscribeDescOverdueDays.Default.(int)
	// subscribeDescRemaining is the schema descriptor for remaining field.
	subscribeDescRemaining := subscribeFields[11].Descriptor()
	// subscribe.DefaultRemaining holds the default value on creation for the remaining field.
	subscribe.DefaultRemaining = subscribeDescRemaining.Default.(int)
	subscribealterMixin := schema.SubscribeAlter{}.Mixin()
	subscribealterMixinHooks2 := subscribealterMixin[2].Hooks()
	subscribealter.Hooks[0] = subscribealterMixinHooks2[0]
	subscribealterMixinFields0 := subscribealterMixin[0].Fields()
	_ = subscribealterMixinFields0
	subscribealterFields := schema.SubscribeAlter{}.Fields()
	_ = subscribealterFields
	// subscribealterDescCreatedAt is the schema descriptor for created_at field.
	subscribealterDescCreatedAt := subscribealterMixinFields0[0].Descriptor()
	// subscribealter.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscribealter.DefaultCreatedAt = subscribealterDescCreatedAt.Default.(func() time.Time)
	// subscribealterDescUpdatedAt is the schema descriptor for updated_at field.
	subscribealterDescUpdatedAt := subscribealterMixinFields0[1].Descriptor()
	// subscribealter.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscribealter.DefaultUpdatedAt = subscribealterDescUpdatedAt.Default.(func() time.Time)
	// subscribealter.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscribealter.UpdateDefaultUpdatedAt = subscribealterDescUpdatedAt.UpdateDefault.(func() time.Time)
	subscribepauseMixin := schema.SubscribePause{}.Mixin()
	subscribepauseMixinHooks2 := subscribepauseMixin[2].Hooks()
	subscribepause.Hooks[0] = subscribepauseMixinHooks2[0]
	subscribepauseMixinFields0 := subscribepauseMixin[0].Fields()
	_ = subscribepauseMixinFields0
	subscribepauseFields := schema.SubscribePause{}.Fields()
	_ = subscribepauseFields
	// subscribepauseDescCreatedAt is the schema descriptor for created_at field.
	subscribepauseDescCreatedAt := subscribepauseMixinFields0[0].Descriptor()
	// subscribepause.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscribepause.DefaultCreatedAt = subscribepauseDescCreatedAt.Default.(func() time.Time)
	// subscribepauseDescUpdatedAt is the schema descriptor for updated_at field.
	subscribepauseDescUpdatedAt := subscribepauseMixinFields0[1].Descriptor()
	// subscribepause.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscribepause.DefaultUpdatedAt = subscribepauseDescUpdatedAt.Default.(func() time.Time)
	// subscribepause.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscribepause.UpdateDefaultUpdatedAt = subscribepauseDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "v0.10.2-0.20220502113020-4ac82f5bb3f0" // Version of ent codegen.
)
