basePath: /
definitions:
  definition.PersonCertificationFaceRes:
    properties:
      appId:
        description: WBAppid
        type: string
      bindedPhone:
        description: 已绑定的其他手机号
        type: string
      faceId:
        type: string
      licence:
        type: string
      nonce:
        description: 随机字符串
        type: string
      orderNo:
        description: 订单号
        type: string
      sign:
        description: 签名
        type: string
      userId:
        description: 用户唯一标识
        type: string
      version:
        description: 版本号
        type: string
    type: object
  definition.PersonCertificationFaceResultRes:
    properties:
      success:
        description: 是否成功
        type: boolean
    type: object
  definition.PersonCertificationOcrRes:
    properties:
      appId:
        description: WBAppid
        type: string
      nonce:
        description: 随机字符串
        type: string
      orderNo:
        description: 订单号
        type: string
      sign:
        description: 签名
        type: string
      userId:
        description: 用户唯一标识
        type: string
      version:
        description: 版本号
        type: string
    type: object
info:
  contact: {}
  title: 极光出行API - 骑手端api
  version: "2.0"
paths:
  /rider/v2/certification/face:
    post:
      consumes:
      - application/json
      operationId: CertificationFace
      parameters:
      - description: 加密身份信息
        in: query
        name: identity
        type: string
      - description: 身份证国徽面
        in: query
        name: nationalImage
        type: string
      - description: 订单号，用户使用OCR识别时不为空
        in: query
        name: orderNo
        type: string
      - description: 身份证人像面
        in: query
        name: portraitImage
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/definition.PersonCertificationFaceRes'
      summary: 提交身份信息并获取人脸核身参数
      tags:
      - Person - 实人
  /rider/v2/certification/face/result:
    get:
      consumes:
      - application/json
      operationId: CertificationFaceResult
      parameters:
      - description: 订单号
        in: query
        name: orderNo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/definition.PersonCertificationFaceResultRes'
      summary: 获取人脸核身结果
      tags:
      - Person - 实人
  /rider/v2/certification/ocr:
    get:
      consumes:
      - application/json
      operationId: CertificationOcr
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/definition.PersonCertificationOcrRes'
      summary: 获取人脸核身OCR参数
      tags:
      - Person - 实人
swagger: "2.0"
