basePath: /
definitions:
  definition.PersonCertificationFaceRes:
    properties:
      appId:
        description: WBAppid
        type: string
      faceId:
        type: string
      licence:
        type: string
      nonce:
        description: 随机字符串
        type: string
      orderNo:
        description: 订单号
        type: string
      sign:
        description: 签名
        type: string
      userId:
        description: 用户唯一标识
        type: string
      version:
        description: 版本号
        type: string
    type: object
  definition.PersonCertificationFaceResultRes:
    properties:
      success:
        description: 是否成功
        type: boolean
    type: object
  definition.PersonCertificationOcrRes:
    properties:
      appId:
        description: WBAppid
        type: string
      nonce:
        description: 随机字符串
        type: string
      orderNo:
        description: 订单号
        type: string
      sign:
        description: 签名
        type: string
      userId:
        description: 用户唯一标识
        type: string
      version:
        description: 版本号
        type: string
    type: object
  model.AliyunOssStsRes:
    properties:
      accessKeyId:
        type: string
      accessKeySecret:
        type: string
      bucket:
        type: string
      expiration:
        type: string
      region:
        type: string
      stsToken:
        type: string
    type: object
  model.SmsReq:
    properties:
      captchaCode:
        description: captcha 验证码
        type: string
      phone:
        description: 手机号
        type: string
    required:
    - captchaCode
    - phone
    type: object
  model.SmsRes:
    properties:
      id:
        description: 任务ID
        type: string
    type: object
info:
  contact: {}
  description: |
    ### 说明
    接口采用非标准Restful API，所有http返回代码均为`200`，当返回为非`200`时应为network错误，需要及时排查。
    <br>
    接口返回说明查看 **[返回](#返回)**
    <br>
    图片/附件前缀 `https://cdn.auroraride.com/`

    <br />

    <br />

    ### 接口编号

    第一位代表接口端分类

    - M 管理端
    - R 骑手端
    - E 门店端
    - C 通用

    第二位代表子分类（36进制）

    后三位代表子编号（10进制）

    <br />

    <br />


    ### 认证
    项目接口使用简单认证，认证方式为`header`中添加对应的认证`token`
    |  header   |  类型  |  接口  |
    | :-----: | :----: | :--: |
    |  X-Rider-Token   |  string   |  骑手API  |
    | X-Manager-Token | string |  后台API  |
    |  X-Employee-Token   | string |  员工API  |

    <br />

    <br />

    ### 返回

    一个标准的返回应包含以下结构

    |  字段   |  类型  |  必填  |  说明  |
    | :-----: | :----: | :--: | :--: |
    |  code   |  int   |  是  |  返回代码  |
    | message | string |  是  |  返回消息  |
    |  data   | object |  是  |  返回数据  |

    `code`代码取值说明

    | 十进制 | 十六进制 | 说明 |
    | :----: | :------: | :--: |
    | 0  |  0x000  | 请求成功 |
    | 256 |  0x100  | 请求失败 |
    | 512 |  0x200  | *需要认证(跳转登录) |
    | 768 |  0x300  | *用户被封禁 |
    | 1024 |  0x400  | 资源未获 |
    | 1280 |  0x500  | 未知错误 |
    | 1536 |  0x600  | *需要实名 |
    | 1792 |  0x700  | *需要验证 (更换设备, 需要人脸验证) |
    | 2048 |  0x800  | *需要联系人 |
    | 2304 |  0x900  | 请求过期 |

    > 当返回值是`1792(0x700)需要人脸验证`或`1536(0x600)需要实名`的时候`data`返回值为`{"url": "string"}`, 直接跳转url


    比如：
    > 默认成功返回
    ```json
    {
      "code": 0,
      "message": "OK",
      "data": {
        "status": true
      }
    }
    ```
  title: 极光出行API - 骑手端api
  version: "2.0"
paths:
  /common/captcha:
    get:
      consumes:
      - image/png
      description: 生成的图片验证码有效时间为10分钟
      operationId: CaptchaGenerate
      produces:
      - image/png
      responses:
        "200":
          description: ok
          headers:
            "X-Captcha-Id\ttrue":
              description: Captcha验证码ID
              type: string
          schema:
            type: string
      summary: C1 生成图片验证码
      tags:
      - Communal - 公共接口
  /common/oss/token:
    get:
      consumes:
      - application/json
      description: 上传文件必须，单次获取有效时间为1个小时
      operationId: AliyunOssToken
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.AliyunOssStsRes'
      summary: C3 获取阿里云oss临时凭证
      tags:
      - Communal - 公共接口
  /common/sms:
    post:
      consumes:
      - application/json
      description: 上传文件必须，单次获取有效时间为1个小时
      operationId: SendSmsCode
      parameters:
      - description: 请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SmsReq'
      - description: Captcha验证码ID
        in: header
        name: X-Captcha-Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.SmsRes'
      summary: C2 发送短信验证码
      tags:
      - Communal - 公共接口
  /v2/certification/face:
    get:
      consumes:
      - application/json
      operationId: CertificationFace
      parameters:
      - description: '身份信息 // TODO: 加密传输'
        in: query
        name: identity
        required: true
        type: string
      - description: 订单号，用户使用OCR识别时不为空
        in: query
        name: orderNo
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/definition.PersonCertificationFaceRes'
      summary: 获取人脸核身参数
      tags:
      - Person - 实人
  /v2/certification/face/result:
    get:
      consumes:
      - application/json
      operationId: CertificationFaceResult
      parameters:
      - description: 订单号
        in: query
        name: orderNo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/definition.PersonCertificationFaceResultRes'
      summary: 获取实人核身结果
      tags:
      - Person - 实人
  /v2/certification/ocr:
    get:
      consumes:
      - application/json
      operationId: CertificationOcr
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/definition.PersonCertificationOcrRes'
      summary: 获取人脸核身OCR参数
      tags:
      - Person - 实人
swagger: "2.0"
