basePath: /
definitions:
  model.AliyunOssStsRes:
    properties:
      accessKeyId:
        type: string
      accessKeySecret:
        type: string
      bucket:
        type: string
      expiration:
        type: string
      region:
        type: string
      stsToken:
        type: string
    type: object
  model.Branch:
    properties:
      address:
        type: string
      cityId:
        type: integer
      contracts:
        items:
          $ref: '#/definitions/model.BranchContract'
        type: array
      creator:
        $ref: '#/definitions/model.Modifier'
      lastModifier:
        $ref: '#/definitions/model.Modifier'
      lat:
        type: number
      lng:
        type: number
      name:
        type: string
      photos:
        items:
          type: string
        type: array
    required:
    - address
    - cityId
    - lat
    - lng
    - name
    - photos
    type: object
  model.BranchContract:
    properties:
      area:
        type: number
      bankNumber:
        type: string
      electricity:
        type: number
      electricityPledge:
        type: number
      endTime:
        type: string
      file:
        type: string
      idCardNumber:
        type: string
      landlordName:
        type: string
      lease:
        type: integer
      phone:
        type: string
      pledge:
        type: number
      rent:
        type: number
      sheets:
        items:
          type: string
        type: array
      startTime:
        type: string
    required:
    - area
    - bankNumber
    - electricity
    - electricityPledge
    - endTime
    - file
    - idCardNumber
    - landlordName
    - lease
    - phone
    - pledge
    - rent
    - sheets
    - startTime
    type: object
  model.CityItem:
    properties:
      children:
        description: 城市列表
        items:
          $ref: '#/definitions/model.CityItem'
        type: array
      id:
        description: 城市或省份ID
        type: integer
      name:
        description: 城市/省份
        type: string
      open:
        description: 是否启用
        type: boolean
    type: object
  model.CityModifyReq:
    properties:
      id:
        type: integer
      open:
        type: boolean
    required:
    - id
    - open
    type: object
  model.ManagerSigninRes:
    properties:
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      token:
        type: string
    type: object
  model.Modifier:
    properties:
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    type: object
  model.Pagination:
    properties:
      current:
        description: 当前页
        type: integer
      pages:
        description: 总页数
        type: integer
      total:
        description: 总条数
        type: integer
    type: object
  model.PaginationRes:
    properties:
      items:
        description: 返回数据
        type: any
      pagination:
        $ref: '#/definitions/model.Pagination'
        description: 分页属性
    type: object
  model.ShiguangjuIVRItem:
    properties:
      name:
        description: 姓名
        type: string
      phone:
        description: 手机号
        type: string
      product:
        description: 套餐
        type: string
      status:
        description: 外呼状态
        type: boolean
    type: object
  model.ShiguangjuIVRRes:
    properties:
      items:
        items:
          $ref: '#/definitions/model.ShiguangjuIVRItem'
        type: array
    type: object
  model.SmsReq:
    properties:
      captchaCode:
        description: captcha 验证码
        type: string
      phone:
        description: 手机号
        type: string
    required:
    - captchaCode
    - phone
    type: object
  model.SmsRes:
    properties:
      id:
        description: 任务ID
        type: string
    type: object
  model.StatusResponse:
    properties:
      status:
        type: boolean
    type: object
info:
  contact: {}
  description: |-
    ### 说明
    接口采用非标准Restful API，所有http返回代码均为`200`，当返回为非`200`时应为network错误，需要及时排查。
    <br>
    接口返回说明查看 **[返回](#返回)**

    ### 认证
    项目接口使用简单认证，认证方式为`header`中添加对应的认证`token`
    |  header   |  类型  |  接口  |
    | :-----: | :----: | :--: |
    |  X-Rider-Token   |  string   |  骑手API  |
    | X-Manager-Token | string |  后台API  |
    |  X-Employee-Token   | string |  员工API  |

    ### 返回
    一个标准的返回应包含以下结构

    |  字段   |  类型  |  必填  |  说明  |
    | :-----: | :----: | :--: | :--: |
    |  code   |  int   |  是  |  返回代码  |
    | message | string |  是  |  返回消息  |
    |  data   | object |  是  |  返回数据  |

    `code`代码取值说明

    | 二进制 | 十六进制 | 说明 |
    | :----: | :------: | :--: |
    | 0  |  0x000  | 请求成功 |
    | 256 |  0x100  | 请求失败 |
    | 512 |  0x200  | 需要认证 (需要登录) |
    | 768 |  0x300  | 没有权限 |
    | 1024 |  0x400  | 资源未获 |
    | 1280 |  0x500  | 未知错误 |
    | 1536 |  0x600  | 需要实名 |
    | 1792 |  0x700  | 需要验证 (更换设备需要人脸验证) |
    | 2048 |  0x800  | 需要联系人 |
    | 2304 |  0x900  | 请求过期 |


    比如：
    > 默认成功返回
    ```json
    {
      "code": 0,
      "message": "OK",
      "data": {
        "status": true
      }
    }
    ```
  title: 极光出行API
  version: "1.0"
paths:
  /commom/sms:
    post:
      consumes:
      - application/json
      description: 上传文件必须，单次获取有效时间为1个小时
      operationId: SendSmsCode
      parameters:
      - description: 请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SmsReq'
      - description: Captcha验证码ID
        in: header
        name: X-Captcha-Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.SmsRes'
      summary: C2.发送短信验证码
      tags:
      - '[C]公共接口'
  /common/captcha:
    get:
      consumes:
      - image/png
      description: 生成的图片验证码有效时间为10分钟
      operationId: CaptchaGenerate
      produces:
      - image/png
      responses:
        "200":
          description: ok
          headers:
            X-Captcha-Id:
              description: Captcha验证码ID
              type: string
          schema:
            type: string
      summary: C1.生成图片验证码
      tags:
      - '[C]公共接口'
  /common/oss/token:
    get:
      consumes:
      - application/json
      description: 上传文件必须，单次获取有效时间为1个小时
      operationId: AliyunOssToken
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.AliyunOssStsRes'
      summary: C3.获取阿里云oss临时凭证
      tags:
      - '[C]公共接口'
  /manager/v1/{id}/contract:
    post:
      consumes:
      - application/json
      operationId: BranchAddContract
      parameters:
      - description: 管理员校验token
        in: header
        name: X-Manager-Token
        required: true
        type: string
      - description: 合同数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.BranchContract'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.StatusResponse'
      summary: M3.4 新增合同
      tags:
      - '[M]管理接口'
  /manager/v1/branch:
    get:
      consumes:
      - application/json
      operationId: BranchList
      parameters:
      - description: 管理员校验token
        in: header
        name: X-Manager-Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/model.PaginationRes'
            - properties:
                items:
                  items:
                    $ref: '#/definitions/model.Branch'
                  type: array
              type: object
      summary: M3.1 网点列表
      tags:
      - '[M]管理接口'
    post:
      consumes:
      - application/json
      operationId: BranchAdd
      parameters:
      - description: 管理员校验token
        in: header
        name: X-Manager-Token
        required: true
        type: string
      - description: 网点数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Branch'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.StatusResponse'
      summary: M3.2 新增网点
      tags:
      - '[M]管理接口'
  /manager/v1/branch/{id}:
    put:
      consumes:
      - application/json
      operationId: BranchModify
      parameters:
      - description: 管理员校验token
        in: header
        name: X-Manager-Token
        required: true
        type: string
      - description: 网点数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Branch'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.StatusResponse'
      summary: M3.3 编辑网点
      tags:
      - '[M]管理接口'
  /manager/v1/city:
    get:
      consumes:
      - application/json
      parameters:
      - description: 管理员校验token
        in: header
        name: X-Manager-Token
        required: true
        type: string
      - description: 启用状态 0:全部 1:未启用 2:已启用
        in: query
        maximum: 2
        minimum: 0
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            items:
              $ref: '#/definitions/model.CityItem'
            type: array
      summary: M2.1 城市列表
      tags:
      - '[M]管理接口'
  /manager/v1/city/{id}:
    put:
      consumes:
      - application/json
      description: desc
      operationId: CityModify
      parameters:
      - description: 管理员校验token
        in: header
        name: X-Manager-Token
        required: true
        type: string
      - description: 城市ID
        in: path
        name: id
        required: true
        type: integer
      - description: 城市数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.CityModifyReq'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.StatusResponse'
      summary: M2.2 修改城市
      tags:
      - '[M]管理接口'
  /manager/v1/csc/irv:
    post:
      consumes:
      - multipart/form-data
      operationId: CscIvrShiguangju
      parameters:
      - description: 管理员校验token
        in: header
        name: X-Manager-Token
        required: true
        type: string
      - description: 外呼文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.ShiguangjuIVRRes'
      summary: MT1. 时光驹催费工具
      tags:
      - '[M]管理接口'
  /manager/v1/user/signin:
    post:
      consumes:
      - application/json
      description: 管理员登录
      operationId: ManagerSignin
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.ManagerSigninRes'
      summary: M1.1 用户登录
      tags:
      - '[M]管理接口'
swagger: "2.0"
