app:
  address: :5533
  bodylimit: 50M
  ratelimit: 20

logging:
  color: true
  level: info
  age: 8192
  json: false

nsq:
  url: 127.0.0.1:4150

database:
  postgres:
    dsn: 'host=localhost user=user password=password dbname=db port=5432 sslmode=disable TimeZone=Asia/Shanghai'

third_party:
  yunfuture:
    token: mUVvyHyZFBzWqwjSyXtVfmpCFxAUMHMK
