app:
  address: :5533
  bodylimit: 50M
  ratelimit: 20
  captcha:
    names:
      - 'rider-signin': 'RIDER_SIGNIN'

logging:
  color: true
  level: info
  age: 8192
  json: false

nsq:
  url: 127.0.0.1:4150

database:
  postgres:
    dsn: 'host=localhost user=user password=password dbname=db port=5432 sslmode=disable TimeZone=Asia/Shanghai'
  redis:
    addr: 'localhost:6379'
    password: ''
    db: 0

third_party:
  yunfuture:
    token: mUVvyHyZFBzWqwjSyXtVfmpCFxAUMHMK

aliyun:
  sms:
    accessId: ''
    accessSecret: ''
    endpoint: 'dysmsapi.aliyuncs.com'
    sign: 时光驹
    template:
      general: # 通用验证码模板
        code: ''
