# https://github.com/jeremyhuiskamp/golang-docker-scratch/blob/main/Dockerfile.externaltz

name: Docker build dev
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploye:
    name: Build docker development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Alibaba Cloud Container Registry
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{secrets.ACR_LOGINSERVER}}
          region-id: ${{secrets.ACR_REGIONID}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: registry.cn-beijing.aliyuncs.com/liasica/aurservd:dev